import requests
from bs4 import BeautifulSoup

r = requests.get('https://en.wikipedia.org/wiki/List_of_Game_of_Thrones_characters')
s = BeautifulSoup(r.text, 'html.parser')

tables = s.find_all('table', {'class': 'wikitable'})

def get_characters_from_tables(table):
    rows = table.find_all('tr')[2:]
    characters = set()
    for row in rows:
        character = row.find_all('td')[1].text
        characters.add(character)
    return characters


CHARACTERS = {'Alliser Thorne',
 'Alton Lannister',
 'Alys Karstark',
 'Amory Lorch',
 'Anguy',
 'Archmaester Ebrose',
 'Areo Hotah',
 'Arya Stark',
 'Barristan Selmy',
 'Benjen Stark',
 'Beric Dondarrion',
 'Biter',
 'Black Lorren',
 'Walder Rivers',
 'Bobono',
 'Bowen Marsh',
 'Bran Stark',
 'Brienne of Tarth',
 'Bronn',
 'Brynden Tully',
 'Catelyn Stark',
 'Cersei Lannister',
 'Clarenzo',
 'Craster',
 'Daario Naharis',
 'Daenerys Targaryen',
 'Dagmer Cleftjaw',
 'Daisy',
 'Davos Seaworth',
 'Dickon Tarly',
 'Dontos Hollard',
 'Doran Martell',
 'Doreah',
 'Eddard "Ned" Stark',
 'Eddison Tollett',
 'Edmure Tully',
 'Ellaria Sand',
 'Euron Greyjoy',
 'Gendry',
 'Gilly',
 'Grand Maester Pycelle',
 'Greatjon Umber',
 'Gregor "The Mountain" Clegane',
 'Grenn',
 'Grey Worm',
 'Harald Karstark',
 'Harrag',
 'High Septon',
 'Hizdahr zo Loraq',
 'Hodor',
 'Hot Pie',
 'Ilyn Payne',
 'Irri',
 'Izembaro',
 'Jaime Lannister',
 'Janos Slynt',
 "Jaqen H'ghar",
 'Jeor Mormont',
 'Joffrey Baratheon',
 'Jojen Reed',
 'Jon Snow',
 'Jorah Mormont',
 'Jory Cassel',
 'Kevan Lannister',
 'Drogo',
 'Moro',
 'Kovarro',
 'Kraznys mo Nakloz',
 'Lady Crane',
 'Lancel Lannister',
 'Leaf',
 'Little Sam',
 'Locke',
 'Lommy Greenhands',
 'Loras Tyrell',
 'Lothar Frey',
 'Lyanna Mormont',
 'Lysa Arryn',
 'Mace Tyrell',
 'Aemon',
 'Luwin',
 'Wolkan',
 'Mance Rayder',
 'Margaery Tyrell',
 'Marillion',
 'Meera Reed',
 'Melisandre',
 'Meryn Trant',
 'Mirri Maz Duur',
 'Missandei',
 'Myranda',
 'Myrcella Baratheon',
 'Night King',
 'Nymeria Sand',
 'Obara Sand',
 'Oberyn Martell',
 'Olenna Tyrell',
 'Olly',
 'Olyvar',
 'Orell',
 'Osha',
 'Othell Yarwyck',
 'Petyr "Littlefinger" Baelish',
 'Podrick Payne',
 'Pyat Pree',
 'Pypar',
 'Qhono',
 'Qhorin Halfhand',
 'Qotho',
 'Qyburn',
 'Rakharo',
 'Ramsay Bolton',
 'Randyll Tarly',
 'Rast',
 'Renly Baratheon',
 'Rickard Karstark',
 'Rickon Stark',
 'Robb Stark',
 'Robert Baratheon',
 'Robett Glover',
 'Robin Arryn',
 'Rodrik Cassel',
 'Roose Bolton',
 'Rorge',
 'Ros',
 'Samwell Tarly',
 'Sandor "The Hound" Clegane',
 'Sansa Stark',
 'Selyse Florent',
 'Mordane',
 'Unella',
 'Shae',
 'Shireen Baratheon',
 'Silk King',
 'Spice King',
 'Stannis Baratheon',
 'Steelshanks Walton',
 'Styr',
 'Syrio Forel',
 'Talisa Maegyr',
 'High Sparrow',
 'Waif',
 'Thenn Warg',
 'Theon Greyjoy',
 'Thoros of Myr',
 'Three-Eyed Raven',
 'Tommen Baratheon',
 'Tormund Giantsbane',
 'Trystane Martell',
 'Tyene Sand',
 'Tyrion Lannister',
 'Tywin Lannister',
 'Varys',
 'Viserys Targaryen',
 'Walda Bolton',
 'Wun Weg Wun Dar Wun',
 'Xaro Xhoan Daxos',
 'Yara Greyjoy',
 'Ygritte',
 'Yohn Royce',
 'Yoren'}

firstnames = set()

for s in CHARACTERS:
    if s == 'Wun Weg Wun Dar Wun':
        firstnames.add(s)
    else:
        fname = s.split(' ')[0]
        if fname == 'High':
            firstnames.add(s)
        else:
            firstnames.add(fname)
